---
title: "Actividad 1.3"
author: "Lucero Díaz"
date: "2026-09-24"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problema 1

Dadas las matrices A y B:

$$ A = \begin{bmatrix} 2 & 4 & -3 \\ 0 & -2 & 5 \\ 9 & 0 & 6 \end{bmatrix} $$

$$ B = \begin{bmatrix} 8 & 6 & -2 \\ -7 & 9 & -5 \\ -3 & 5 & 1 \end{bmatrix} $$

Calcula:

```{r}
# Definición de matrices
A <- matrix(c(2, 4, -3, 
              0, -2, 5, 
              9, 0, 6), ncol=3, byrow = TRUE)
B <- matrix(c(8, 6, -2, 
              -7, 9, -5, 
              -3, 5, 1), ncol=3, byrow = TRUE)
```

```{r}
library(expm)

# a) A + B
cat("A+B \n")
print(A+B)

# b) 4A + 3B
cat("\n4A + 3B \n")
print(4*A + 3*B)

# c) A'
cat("\nA' \n")
print(t(A))

# d) A^(-1)
cat("\nA^(-1) \n")
print(solve(A))

# e) Determinante de A y A'
cat("\nDeterminante de A \n")
print(det(A))

cat("\nDeterminante de A' \n")
print(det(t(A)))

```


## Problema 2

```{r}
A <- matrix(c(2, 1, 3, -3, 
              3, 0, -2, -1, 
              4, 5, 0, -5), ncol=4, byrow = TRUE)
B <- matrix(c(4, 2, 
              -3, 1, 
              5, -2, 
              8, 0), ncol=2, byrow = TRUE)
```

```{r}
# Multiplicacion
print(A%*%B)
```


## Problema 3

```{r}

```


